return {
  "folke/todo-comments.nvim",
  dependencies = "nvim-lua/plenary.nvim",
  event = "BufReadPre",
  opts = {
    keywords = {
      FIX = { icon = " ", color = "error", alt = { "FIXME", "BUG", "FIXIT", "ISSUE" } },
      TODO = { icon = " ", color = "info" },
      HACK = { icon = " ", color = "warning" },
      WARN = { icon = " ", color = "warning", alt = { "WARNING", "XXX" } },
      PERF = { icon = " ", color = "default", alt = { "OPTIM", "PERFORMANCE", "OPTIMIZE" } },
      NOTE = { icon = " ", color = "hint", alt = { "INFO" } },
      TEST = { icon = "⏲ ", color = "test" },
      REVIEW = { icon = " ", color = "info", alt = { "CODE_REVIEW" } },
      REFACTOR = { icon = " ", color = "default", alt = { "CLEANUP" } },
      DEBUG = { icon = " ", color = "error", alt = { "DEBUGGING" } },
      SECURITY = { icon = " ", color = "error", alt = { "SEC", "VULN" } },
      DEPRECATED = { icon = " ", color = "warning", alt = { "DEPRECATE" } },
      DOCS = { icon = " ", color = "hint", alt = { "DOCUMENTATION" } },
      IDEA = { icon = " ", color = "hint" },
      TEMP = { icon = " ", color = "warning", alt = { "TEMPORARY", "TMP" } },
      DONE = { icon = " ", color = "done", alt = { "COMPLETED", "FINISHED" } },
      PASSED = { icon = " ", color = "done", alt = { "SUCCESS" } },
      FAILED = { icon = " ", color = "error" },
      SKIP = { icon = " ", color = "warning", alt = { "SKIPPED" } },
    },
    colors = {
      error = { "DiagnosticError", "ErrorMsg", "#DC2626" },
      warning = { "DiagnosticWarn", "WarningMsg", "#FBBF24" },
      info = { "DiagnosticInfo", "#2563EB" },
      hint = { "DiagnosticHint", "#10B981" },
      default = { "Identifier", "#7C3AED" },
      test = { "Identifier", "#FF00FF" },
      done = { "DiagnosticOk", "#22C55E" },
    },
  },
}
